[build]
  command = "npm i"
  functions = "src/functions"

[template.environment]
  FOXY_TIMEZONE = "Foxy store timezone, as in `America/Los_Angeles`. Full list: https://tinyurl.com/yxoaxbpz"
  FOXY_API_CLIENT_ID = "Enter your Foxy.io API Client ID here."
  FOXY_API_CLIENT_SECRET = "Enter your Foxy.io API Client Secret here."
  FOXY_API_REFRESH_TOKEN = "Enter your Foxy.io API Refresh Token here."
  DEFAULT_AUTOSHIP_FREQUENCY = "Default autoship frequency (such as `1m`)"
  IDEV_SECRET_KEY = "iDevAffiliate secret key (from the API settings)"
  IDEV_API_URL = "iDevAffiliate API URL (from the API settings; should end in `sale.php`)"
  WEBFLOW_TOKEN = "Webflow Token (from Webflow's project settings, at the 'Integrations' tab)"
